name: Update stat cards

# Run daily at 01:00 UTC
on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card (dark version)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=10&bg_color=00000000&title_color=51aeddff&text_color=ffffffff&hide_border=true
          path: images/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card (light version)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=10&bg_color=00000000&title_color=51aeddff&text_color=000000ff&hide_border=true
          path: images/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add images/*.svg
          git commit -m "chore: update stat cards" || exit 0
          git push
